TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .proto file
DATA += devinstron.proto

DB += controls.db 
DB += controls_channel.db 
DB += controls_channel_specific.db
DB += controls_waveform.db
DB += logging.db

#=======================================
include $(TOP)/configure/RULES
