TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .proto file
DATA += devinstron.proto

#=======================================
include $(TOP)/configure/RULES
