TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .proto file
DATA += $(TOP)/instronSup/devinstron.proto

#=======================================
include $(TOP)/configure/RULES
